core/linux-raspberrypi4 to 5.10.rc3-1
Trying out 5.10.y tree here... make sure not to set aegis128 in config
due to build errors:

crypto/aegis128-neon-inner.c: In function ‘crypto_aegis128_init_neon’:
crypto/aegis128-neon-inner.c:151:3: error: incompatible types when initializing type ‘unsigned char’ using type ‘uint8x16_t’
  151 |   k ^ vld1q_u8(const0),
      |   ^
crypto/aegis128-neon-inner.c:152:3: error: incompatible types when initializing type ‘unsigned char’ using type ‘uint8x16_t’
  152 |   k ^ vld1q_u8(const1),